# Generated by Django 5.0.4 on 2026-07-12 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0037_remove_lead_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('job_title', models.CharField(blank=True, max_length=150, null=True)),
                ('date_of_joining', models.DateField(blank=True, null=True)),
                ('salary_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('bank_account_details', models.TextField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profiles', to='crm.organization')),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to='crm.userprofile')),
            ],
            options={
                'db_table': 'hr_employee_profiles',
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('Sick', 'Sick Leave'), ('Vacation', 'Vacation'), ('Personal', 'Personal Leave'), ('Unpaid', 'Unpaid Leave')], default='Vacation', max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('applied_on', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='crm.organization')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='crm.userprofile')),
            ],
            options={
                'db_table': 'hr_leave_requests',
                'ordering': ['-applied_on'],
            },
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_start_date', models.DateField()),
                ('cycle_end_date', models.DateField()),
                ('base_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('bonuses', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('deductions', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('net_pay', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Processed', 'Processed'), ('Paid', 'Paid')], default='Draft', max_length=20)),
                ('processed_on', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='crm.organization')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='crm.userprofile')),
            ],
            options={
                'db_table': 'hr_payrolls',
                'ordering': ['-processed_on'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('clock_in', models.TimeField(blank=True, null=True)),
                ('clock_out', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Half-Day', 'Half-Day'), ('On Leave', 'On Leave')], default='Present', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_logs', to='crm.organization')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_logs', to='crm.userprofile')),
            ],
            options={
                'db_table': 'hr_attendance',
                'unique_together': {('user_profile', 'date')},
            },
        ),
    ]
