# Generated by Django 5.0.4 on 2026-07-13 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0037_remove_lead_service'),
        ('hr', '0002_attendancestatus_alter_attendance_status_leavetype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequestStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_request_statuses', to='crm.organization')),
            ],
            options={
                'db_table': 'hr_leave_request_statuses',
            },
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.leaverequeststatus'),
        ),
    ]
