# Generated by Django 5.0.4 on 2026-07-18 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0037_remove_lead_service'),
        ('hr', '0003_leaverequeststatus_alter_leaverequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='crm.department'),
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designations', to='crm.organization')),
            ],
            options={
                'db_table': 'hr_designations',
            },
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='hr.designation'),
        ),
    ]
