# Generated by Django 5.0.4 on 2026-07-19 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_employeeprofile_department_designation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='designation',
        ),
        migrations.DeleteModel(
            name='Designation',
        ),
    ]
