# Generated by Django 5.0.4 on 2026-07-19 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_remove_employeeprofile_designation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='job_title',
        ),
    ]
