# Generated by Django 5.0.4 on 2026-08-14 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_remove_employeeprofile_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='advance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
