# Generated by Django 5.2.15 on 2026-06-20 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='plan',
        ),
        migrations.DeleteModel(
            name='EmailTemplate',
        ),
        migrations.DeleteModel(
            name='HelpArticle',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='user_profile',
        ),
        migrations.DeleteModel(
            name='BillingPlan',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
