# Generated by Django 5.2.15 on 2026-06-20 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_remove_unused_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='alt_phone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='last_followup_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
