# Generated by Django 5.2.15 on 2026-06-22 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_lead_alt_phone_number_lead_date_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(default='New', max_length=50),
        ),
        migrations.CreateModel(
            name='LeadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(choices=[('blue', 'Blue'), ('grey', 'Grey'), ('green', 'Green'), ('yellow', 'Yellow'), ('red', 'Red')], default='blue', max_length=20)),
                ('position', models.IntegerField(default=0)),
                ('is_default', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_statuses', to='crm.organization')),
            ],
            options={
                'ordering': ['position', 'id'],
                'unique_together': {('organization', 'name')},
            },
        ),
    ]
