# Generated by Django 5.2.15 on 2026-06-23 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_alter_lead_status_leadstatus'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='activity',
            table='activities',
        ),
        migrations.AlterModelTable(
            name='event',
            table='events',
        ),
        migrations.AlterModelTable(
            name='lead',
            table='leads',
        ),
        migrations.AlterModelTable(
            name='leadstatus',
            table='lead_statuses',
        ),
        migrations.AlterModelTable(
            name='meeting',
            table='meetings',
        ),
        migrations.AlterModelTable(
            name='organization',
            table='organizations',
        ),
        migrations.AlterModelTable(
            name='task',
            table='tasks',
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='user_profiles',
        ),
    ]
