# Generated by Django 5.2.15 on 2026-06-26 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_alter_activity_table_alter_event_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
