# Generated by Django 5.2.15 on 2026-06-26 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_add_location_to_lead'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_roles', to='crm.organization')),
            ],
            options={
                'db_table': 'staff_roles',
                'unique_together': {('organization', 'name')},
            },
        ),
    ]
