# Generated by Django 5.2.15 on 2026-06-27 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_create_default_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='paid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='leadstatus',
            name='color',
            field=models.CharField(default='#0053db', max_length=20),
        ),
    ]
