# Generated by Django 5.2.15 on 2026-06-27 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0020_quotation_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationitem',
            name='quotation',
        ),
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement_number', models.CharField(max_length=50, unique=True)),
                ('date', models.DateField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('client_name', models.CharField(max_length=255)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('client_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('client_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('client_address', models.TextField(blank=True, null=True)),
                ('project_name', models.CharField(max_length=255)),
                ('monthly_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('advance_payment', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('payment_cycle', models.CharField(default='Monthly', max_length=100)),
                ('payment_method', models.CharField(default='Bank Transfer', max_length=100)),
                ('posts_count', models.IntegerField(default=0)),
                ('campaigns_count', models.IntegerField(default=0)),
                ('revisions', models.IntegerField(default=3)),
                ('notice_period', models.IntegerField(default=30)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='Draft', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='crm.organization')),
            ],
            options={
                'db_table': 'agreements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgreementService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='crm.agreement')),
            ],
            options={
                'db_table': 'agreement_services',
            },
        ),
        migrations.CreateModel(
            name='ClientResponsibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsibility', models.TextField()),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsibilities', to='crm.agreement')),
            ],
            options={
                'db_table': 'client_responsibilities',
            },
        ),
        migrations.CreateModel(
            name='Deliverable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='crm.agreement')),
            ],
            options={
                'db_table': 'deliverables',
            },
        ),
        migrations.DeleteModel(
            name='Quotation',
        ),
        migrations.DeleteModel(
            name='QuotationItem',
        ),
    ]
