# Generated by Django 5.2.15 on 2026-06-27 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0021_remove_quotationitem_quotation_agreement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agreement',
            name='project_name',
        ),
        migrations.AddField(
            model_name='agreement',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agreements', to='crm.service'),
        ),
    ]
