# Generated by Django 5.2.15 on 2026-06-27 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0022_remove_agreement_project_name_agreement_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Planning', 'Planning'), ('Active', 'Active'), ('Completed', 'Completed')], default='Planning', max_length=50)),
                ('leads_generated', models.IntegerField(default=0)),
                ('spend', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='crm.organization')),
            ],
            options={
                'db_table': 'campaigns',
                'ordering': ['-created_at'],
            },
        ),
    ]
