# Generated by Django 5.2.15 on 2026-06-27 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0023_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='color',
            field=models.CharField(default='#004ac6', max_length=50),
        ),
    ]
