# Generated by Django 5.2.15 on 2026-06-27 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0024_event_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffrole',
            name='permissions_json',
            field=models.TextField(default='{}'),
        ),
    ]
