# Generated by Django 5.2.15 on 2026-06-27 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0026_department_userprofile_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(max_length=255)),
                ('date_received', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Editing', 'Editing'), ('Review', 'Review'), ('Approved', 'Approved'), ('Published', 'Published'), ('Rejected', 'Rejected'), ('Scheduled', 'Scheduled')], default='Pending', max_length=50)),
                ('platform', models.CharField(max_length=50)),
                ('upload_date', models.DateField(blank=True, null=True)),
                ('post_type', models.CharField(max_length=50)),
                ('campaign_status', models.CharField(choices=[('Not Started', 'Not Started'), ('Planning', 'Planning'), ('In Progress', 'In Progress'), ('Paused', 'Paused'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Not Started', max_length=50)),
                ('video_link', models.URLField(blank=True, max_length=1000, null=True)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Urgent', 'Urgent')], default='Medium', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_items', to='crm.lead')),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_content', to='crm.userprofile')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_items', to='crm.organization')),
            ],
            options={
                'db_table': 'content_items',
                'ordering': ['-due_date', '-created_at'],
            },
        ),
    ]
