# Generated by Django 5.2.15 on 2026-06-27 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0027_contentitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentDropdownOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('platform', 'Platform'), ('post_type', 'Post Type'), ('status', 'Status'), ('campaign_status', 'Campaign Status'), ('priority', 'Priority')], max_length=50)),
                ('value', models.CharField(max_length=100)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_dropdown_options', to='crm.organization')),
            ],
            options={
                'db_table': 'content_dropdown_options',
                'ordering': ['category', 'display_order', 'value'],
                'unique_together': {('organization', 'category', 'value')},
            },
        ),
    ]
