# Generated by Django 5.2.15 on 2026-06-28 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0028_contentdropdownoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='custom_permissions_json',
            field=models.TextField(default='{}'),
        ),
    ]
