# Generated by Django 5.2.15 on 2026-06-28 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0031_expense_income_partnerpayout'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceCommissionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_commission_types', to='crm.organization')),
            ],
        ),
        migrations.AddField(
            model_name='partnerpayout',
            name='commission_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.financecommissiontype'),
        ),
        migrations.CreateModel(
            name='FinanceExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_expense_categories', to='crm.organization')),
            ],
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.financeexpensecategory'),
        ),
        migrations.CreateModel(
            name='FinancePaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_payment_methods', to='crm.organization')),
            ],
        ),
        migrations.AlterField(
            model_name='expense',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.financepaymentmethod'),
        ),
        migrations.AlterField(
            model_name='income',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.financepaymentmethod'),
        ),
        migrations.AlterField(
            model_name='partnerpayout',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.financepaymentmethod'),
        ),
        migrations.CreateModel(
            name='FinancePaymentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_payment_statuses', to='crm.organization')),
            ],
        ),
        migrations.AlterField(
            model_name='partnerpayout',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.financepaymentstatus'),
        ),
    ]
