# Generated by Django 5.0.4 on 2026-07-05 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0032_financecommissiontype_partnerpayout_commission_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='project_estimation_json',
            field=models.TextField(blank=True, null=True),
        ),
    ]
