# Generated by Django 5.0.4 on 2026-07-08 15:31

import crm.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0033_agreement_project_estimation_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(default='#64748b', max_length=20)),
                ('position', models.IntegerField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_statuses', to='crm.organization')),
            ],
            options={
                'db_table': 'calendar_statuses',
                'ordering': ['position', 'id'],
                'unique_together': {('organization', 'name')},
            },
            bases=(models.Model, crm.models.StatusStyleMixin),
        ),
        migrations.CreateModel(
            name='CampaignStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(default='#64748b', max_length=20)),
                ('position', models.IntegerField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_statuses', to='crm.organization')),
            ],
            options={
                'db_table': 'campaign_statuses',
                'ordering': ['position', 'id'],
                'unique_together': {('organization', 'name')},
            },
            bases=(models.Model, crm.models.StatusStyleMixin),
        ),
        migrations.CreateModel(
            name='ClientStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(default='#64748b', max_length=20)),
                ('position', models.IntegerField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_statuses', to='crm.organization')),
            ],
            options={
                'db_table': 'client_statuses',
                'ordering': ['position', 'id'],
                'unique_together': {('organization', 'name')},
            },
            bases=(models.Model, crm.models.StatusStyleMixin),
        ),
        migrations.CreateModel(
            name='PriorityStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(default='#64748b', max_length=20)),
                ('position', models.IntegerField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='priority_statuses', to='crm.organization')),
            ],
            options={
                'db_table': 'priority_statuses',
                'ordering': ['position', 'id'],
                'unique_together': {('organization', 'name')},
            },
            bases=(models.Model, crm.models.StatusStyleMixin),
        ),
        migrations.CreateModel(
            name='ProjectStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(default='#64748b', max_length=20)),
                ('position', models.IntegerField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_statuses', to='crm.organization')),
            ],
            options={
                'db_table': 'project_statuses',
                'ordering': ['position', 'id'],
                'unique_together': {('organization', 'name')},
            },
            bases=(models.Model, crm.models.StatusStyleMixin),
        ),
        migrations.CreateModel(
            name='TicketStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(default='#64748b', max_length=20)),
                ('position', models.IntegerField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_statuses', to='crm.organization')),
            ],
            options={
                'db_table': 'ticket_statuses',
                'ordering': ['position', 'id'],
                'unique_together': {('organization', 'name')},
            },
            bases=(models.Model, crm.models.StatusStyleMixin),
        ),
    ]
