# Generated by Django 5.0.4 on 2026-07-11 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0034_calendarstatus_campaignstatus_clientstatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='is_client',
            field=models.BooleanField(default=False),
        ),
    ]
