# Generated by Django 5.0.4 on 2026-07-11 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0035_lead_is_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='leads', to='crm.service'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_leads', to='crm.service'),
        ),
    ]
