# Generated by Django 5.0.4 on 2026-07-11 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0036_lead_services_alter_lead_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='service',
        ),
    ]
