# Generated by Django 5.0.4 on 2026-07-21 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0037_remove_lead_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone_number',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
