# Generated by Django 5.0.4 on 2026-08-02 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0041_invoice_amount_paid_invoice_balance_due_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentitem',
            name='campaign_run_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='client_month',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='editor_month',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
