# Generated by Django 5.0.4 on 2026-08-02 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0042_contentitem_campaign_run_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
