# Generated by Django 5.0.4 on 2026-08-03 10:13

import crm.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0043_lead_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.CreateModel(
            name='InvoiceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(default='#64748b', max_length=20)),
                ('position', models.IntegerField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_statuses', to='crm.organization')),
            ],
            options={
                'db_table': 'invoice_statuses',
                'ordering': ['position', 'id'],
                'unique_together': {('organization', 'name')},
            },
            bases=(models.Model, crm.models.StatusStyleMixin),
        ),
    ]
