# Generated by Django 5.0.4 on 2026-08-03 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0044_alter_invoice_status_invoicestatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='crm.lead'),
        ),
    ]
