# Generated by Django 5.0.4 on 2026-08-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0047_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='notified_10h',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='notified_1h',
            field=models.BooleanField(default=False),
        ),
    ]
