# Generated by Django 5.0.4 on 2026-08-07 16:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0048_event_notified_10h_event_notified_1h'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='followup_wanted_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='date_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
