# Generated by Django 5.0.4 on 2026-08-09 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0050_task_progress_task_risk_level_tasktodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_starred',
            field=models.BooleanField(default=False),
        ),
    ]
