# Generated by Django 5.0.4 on 2026-08-14 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0054_agreement_agreement_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentitem',
            name='campaign_status',
        ),
        migrations.RemoveField(
            model_name='contentitem',
            name='upload_date',
        ),
        migrations.RemoveField(
            model_name='contentitem',
            name='video_link',
        ),
    ]
