# Generated by Django 5.0.4 on 2026-08-16 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0055_remove_contentitem_campaign_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentsettings',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
