# Generated by Django 5.0.4 on 2026-08-18 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0057_deletedexpense_deletedincome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentsettings',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=10285.21, max_digits=12),
        ),
    ]
