# Generated by Django 5.0.4 on 2026-08-18 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0058_alter_documentsettings_opening_balance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentsettings',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_phone', models.CharField(max_length=50)),
                ('template_name', models.CharField(blank=True, max_length=100, null=True)),
                ('message_content', models.TextField()),
                ('meta_message_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='Sent', max_length=50)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('buttons_json', models.TextField(default='[]')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_messages', to='crm.lead')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_messages', to='crm.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'whatsapp_messages',
                'ordering': ['-sent_at'],
            },
        ),
    ]
