# Generated by Django 5.0.4 on 2026-08-18 19:13

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Planning', 'Planning'), ('Active', 'Active'), ('Completed', 'Completed'), ('Paused', 'Paused')], default='Active', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('results_count', models.IntegerField(default=0)),
                ('results_type', models.CharField(default='Messaging conversations', max_length=100)),
                ('cost_per_result', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('budget_type', models.CharField(default='Lifetime', max_length=50)),
                ('spend', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('impressions', models.IntegerField(default=0)),
                ('reach', models.IntegerField(default=0)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('platform', models.CharField(default='Meta Ads', max_length=100)),
                ('cost_center', models.CharField(blank=True, max_length=255, null=True)),
                ('leads_generated', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='core.organization')),
            ],
            options={
                'db_table': 'campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(default='#64748b', max_length=20)),
                ('position', models.IntegerField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_statuses', to='core.organization')),
            ],
            options={
                'db_table': 'campaign_statuses',
                'ordering': ['position', 'id'],
                'unique_together': {('organization', 'name')},
            },
            bases=(models.Model, core.models.StatusStyleMixin),
        ),
    ]
